# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import sys
sys.path.append("/home/name1/experiment/eDCC_grpc/grpc_utils/base_package")
import data_pb2 as data__pb2


class CoEdgeServerStub(object):
    """python -m grpc_tools.protoc -I. --python_out=./base_package --grpc_python_out=./base_package ./data.proto
    import sys
    sys.path.append("F:\project\CoEdge_All\CoEdge_1210\grpc_utils\\base_package")

    定义服务,用在rpc传输中
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.allocatedWorkload = channel.unary_unary(
                '/base_package.CoEdgeServer/allocatedWorkload',
                request_serializer=data__pb2.sendWorkloadRequest.SerializeToString,
                response_deserializer=data__pb2.sendWorkloadResponse.FromString,
                )
        self.GetPadding = channel.unary_unary(
                '/base_package.CoEdgeServer/GetPadding',
                request_serializer=data__pb2.paddingrequest.SerializeToString,
                response_deserializer=data__pb2.paddingresponse.FromString,
                )
        self.GetWorkload = channel.unary_unary(
                '/base_package.CoEdgeServer/GetWorkload',
                request_serializer=data__pb2.workloadrequest.SerializeToString,
                response_deserializer=data__pb2.workloadresponse.FromString,
                )
        self.GetResult = channel.unary_unary(
                '/base_package.CoEdgeServer/GetResult',
                request_serializer=data__pb2.resultrequest.SerializeToString,
                response_deserializer=data__pb2.resultresponse.FromString,
                )


class CoEdgeServerServicer(object):
    """python -m grpc_tools.protoc -I. --python_out=./base_package --grpc_python_out=./base_package ./data.proto
    import sys
    sys.path.append("F:\project\CoEdge_All\CoEdge_1210\grpc_utils\\base_package")

    定义服务,用在rpc传输中
    """

    def allocatedWorkload(self, request, context):
        """
        接收初始负载的接口
        接收负载，返回状态码
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPadding(self, request, context):
        """
        获取填充请求的接口
        接收填充请求，返回填充
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkload(self, request, context):
        """
        除工作设备接收全连接计算设备发送来的负载情求
        获取负载请求的接口
        接收负载请求，返回自身工作负载
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResult(self, request, context):
        """
        主设备才需要，用来接收最后的计算结果
        获取结果请求的接口
        接收最终结果
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoEdgeServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'allocatedWorkload': grpc.unary_unary_rpc_method_handler(
                    servicer.allocatedWorkload,
                    request_deserializer=data__pb2.sendWorkloadRequest.FromString,
                    response_serializer=data__pb2.sendWorkloadResponse.SerializeToString,
            ),
            'GetPadding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPadding,
                    request_deserializer=data__pb2.paddingrequest.FromString,
                    response_serializer=data__pb2.paddingresponse.SerializeToString,
            ),
            'GetWorkload': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkload,
                    request_deserializer=data__pb2.workloadrequest.FromString,
                    response_serializer=data__pb2.workloadresponse.SerializeToString,
            ),
            'GetResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResult,
                    request_deserializer=data__pb2.resultrequest.FromString,
                    response_serializer=data__pb2.resultresponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'base_package.CoEdgeServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CoEdgeServer(object):
    """python -m grpc_tools.protoc -I. --python_out=./base_package --grpc_python_out=./base_package ./data.proto
    import sys
    sys.path.append("F:\project\CoEdge_All\CoEdge_1210\grpc_utils\\base_package")

    定义服务,用在rpc传输中
    """

    @staticmethod
    def allocatedWorkload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/base_package.CoEdgeServer/allocatedWorkload',
            data__pb2.sendWorkloadRequest.SerializeToString,
            data__pb2.sendWorkloadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPadding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/base_package.CoEdgeServer/GetPadding',
            data__pb2.paddingrequest.SerializeToString,
            data__pb2.paddingresponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetWorkload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/base_package.CoEdgeServer/GetWorkload',
            data__pb2.workloadrequest.SerializeToString,
            data__pb2.workloadresponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/base_package.CoEdgeServer/GetResult',
            data__pb2.resultrequest.SerializeToString,
            data__pb2.resultresponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
