# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='base_package',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ndata.proto\x12\x0c\x62\x61se_package\"\x88\x01\n\x13sendWorkloadRequest\x12\x10\n\x08workload\x18\x01 \x01(\x0c\x12\x0f\n\x07\x63\x65iling\x18\x02 \x01(\x05\x12\x0e\n\x06\x62ottom\x18\x03 \x01(\x05\x12\x0b\n\x03wid\x18\x04 \x01(\x05\x12\x18\n\x10partition_result\x18\x05 \x03(\x05\x12\x17\n\x0fpartition_index\x18\x06 \x03(\x05\"$\n\x14sendWorkloadResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\"S\n\x0epaddingrequest\x12\x11\n\tpartition\x18\x01 \x01(\x05\x12\x12\n\nup_or_down\x18\x02 \x01(\x05\x12\t\n\x01p\x18\x03 \x01(\x05\x12\x0f\n\x07padding\x18\x04 \x01(\x0c\"5\n\x0fpaddingresponse\x12\x11\n\twait_time\x18\x02 \x01(\x02\x12\x0f\n\x07padding\x18\x01 \x01(\x0c\" \n\x0fworkloadrequest\x12\r\n\x05layer\x18\x01 \x01(\x05\"4\n\x10workloadresponse\x12\x10\n\x08workload\x18\x01 \x01(\x0c\x12\x0e\n\x06height\x18\x02 \x01(\x05\"\x1f\n\rresultrequest\x12\x0e\n\x06result\x18\x01 \x01(\x0c\"\x1e\n\x0eresultresponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x32\xd3\x02\n\x0c\x43oEdgeServer\x12\\\n\x11\x61llocatedWorkload\x12!.base_package.sendWorkloadRequest\x1a\".base_package.sendWorkloadResponse\"\x00\x12K\n\nGetPadding\x12\x1c.base_package.paddingrequest\x1a\x1d.base_package.paddingresponse\"\x00\x12N\n\x0bGetWorkload\x12\x1d.base_package.workloadrequest\x1a\x1e.base_package.workloadresponse\"\x00\x12H\n\tGetResult\x12\x1b.base_package.resultrequest\x1a\x1c.base_package.resultresponse\"\x00\x62\x06proto3'
)




_SENDWORKLOADREQUEST = _descriptor.Descriptor(
  name='sendWorkloadRequest',
  full_name='base_package.sendWorkloadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='workload', full_name='base_package.sendWorkloadRequest.workload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ceiling', full_name='base_package.sendWorkloadRequest.ceiling', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bottom', full_name='base_package.sendWorkloadRequest.bottom', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wid', full_name='base_package.sendWorkloadRequest.wid', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='partition_result', full_name='base_package.sendWorkloadRequest.partition_result', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='partition_index', full_name='base_package.sendWorkloadRequest.partition_index', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=165,
)


_SENDWORKLOADRESPONSE = _descriptor.Descriptor(
  name='sendWorkloadResponse',
  full_name='base_package.sendWorkloadResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='base_package.sendWorkloadResponse.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=203,
)


_PADDINGREQUEST = _descriptor.Descriptor(
  name='paddingrequest',
  full_name='base_package.paddingrequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='partition', full_name='base_package.paddingrequest.partition', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='up_or_down', full_name='base_package.paddingrequest.up_or_down', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='p', full_name='base_package.paddingrequest.p', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='padding', full_name='base_package.paddingrequest.padding', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=288,
)


_PADDINGRESPONSE = _descriptor.Descriptor(
  name='paddingresponse',
  full_name='base_package.paddingresponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='wait_time', full_name='base_package.paddingresponse.wait_time', index=0,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='padding', full_name='base_package.paddingresponse.padding', index=1,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=343,
)


_WORKLOADREQUEST = _descriptor.Descriptor(
  name='workloadrequest',
  full_name='base_package.workloadrequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='layer', full_name='base_package.workloadrequest.layer', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=377,
)


_WORKLOADRESPONSE = _descriptor.Descriptor(
  name='workloadresponse',
  full_name='base_package.workloadresponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='workload', full_name='base_package.workloadresponse.workload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='base_package.workloadresponse.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=431,
)


_RESULTREQUEST = _descriptor.Descriptor(
  name='resultrequest',
  full_name='base_package.resultrequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='base_package.resultrequest.result', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=433,
  serialized_end=464,
)


_RESULTRESPONSE = _descriptor.Descriptor(
  name='resultresponse',
  full_name='base_package.resultresponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='base_package.resultresponse.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=466,
  serialized_end=496,
)

DESCRIPTOR.message_types_by_name['sendWorkloadRequest'] = _SENDWORKLOADREQUEST
DESCRIPTOR.message_types_by_name['sendWorkloadResponse'] = _SENDWORKLOADRESPONSE
DESCRIPTOR.message_types_by_name['paddingrequest'] = _PADDINGREQUEST
DESCRIPTOR.message_types_by_name['paddingresponse'] = _PADDINGRESPONSE
DESCRIPTOR.message_types_by_name['workloadrequest'] = _WORKLOADREQUEST
DESCRIPTOR.message_types_by_name['workloadresponse'] = _WORKLOADRESPONSE
DESCRIPTOR.message_types_by_name['resultrequest'] = _RESULTREQUEST
DESCRIPTOR.message_types_by_name['resultresponse'] = _RESULTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

sendWorkloadRequest = _reflection.GeneratedProtocolMessageType('sendWorkloadRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDWORKLOADREQUEST,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:base_package.sendWorkloadRequest)
  })
_sym_db.RegisterMessage(sendWorkloadRequest)

sendWorkloadResponse = _reflection.GeneratedProtocolMessageType('sendWorkloadResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENDWORKLOADRESPONSE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:base_package.sendWorkloadResponse)
  })
_sym_db.RegisterMessage(sendWorkloadResponse)

paddingrequest = _reflection.GeneratedProtocolMessageType('paddingrequest', (_message.Message,), {
  'DESCRIPTOR' : _PADDINGREQUEST,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:base_package.paddingrequest)
  })
_sym_db.RegisterMessage(paddingrequest)

paddingresponse = _reflection.GeneratedProtocolMessageType('paddingresponse', (_message.Message,), {
  'DESCRIPTOR' : _PADDINGRESPONSE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:base_package.paddingresponse)
  })
_sym_db.RegisterMessage(paddingresponse)

workloadrequest = _reflection.GeneratedProtocolMessageType('workloadrequest', (_message.Message,), {
  'DESCRIPTOR' : _WORKLOADREQUEST,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:base_package.workloadrequest)
  })
_sym_db.RegisterMessage(workloadrequest)

workloadresponse = _reflection.GeneratedProtocolMessageType('workloadresponse', (_message.Message,), {
  'DESCRIPTOR' : _WORKLOADRESPONSE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:base_package.workloadresponse)
  })
_sym_db.RegisterMessage(workloadresponse)

resultrequest = _reflection.GeneratedProtocolMessageType('resultrequest', (_message.Message,), {
  'DESCRIPTOR' : _RESULTREQUEST,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:base_package.resultrequest)
  })
_sym_db.RegisterMessage(resultrequest)

resultresponse = _reflection.GeneratedProtocolMessageType('resultresponse', (_message.Message,), {
  'DESCRIPTOR' : _RESULTRESPONSE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:base_package.resultresponse)
  })
_sym_db.RegisterMessage(resultresponse)



_COEDGESERVER = _descriptor.ServiceDescriptor(
  name='CoEdgeServer',
  full_name='base_package.CoEdgeServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=499,
  serialized_end=838,
  methods=[
  _descriptor.MethodDescriptor(
    name='allocatedWorkload',
    full_name='base_package.CoEdgeServer.allocatedWorkload',
    index=0,
    containing_service=None,
    input_type=_SENDWORKLOADREQUEST,
    output_type=_SENDWORKLOADRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetPadding',
    full_name='base_package.CoEdgeServer.GetPadding',
    index=1,
    containing_service=None,
    input_type=_PADDINGREQUEST,
    output_type=_PADDINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetWorkload',
    full_name='base_package.CoEdgeServer.GetWorkload',
    index=2,
    containing_service=None,
    input_type=_WORKLOADREQUEST,
    output_type=_WORKLOADRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetResult',
    full_name='base_package.CoEdgeServer.GetResult',
    index=3,
    containing_service=None,
    input_type=_RESULTREQUEST,
    output_type=_RESULTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COEDGESERVER)

DESCRIPTOR.services_by_name['CoEdgeServer'] = _COEDGESERVER

# @@protoc_insertion_point(module_scope)
